### ISSUE TITLE
A Simple Request

### ISSUE THREAD

**Issue by gabekiriakos** [nmmarquez/re_simulations#1]
There is no issue. You are free to delete this one.👍

**Comment by nmmarquez** [comment]
no worries. I meant to star yours anyways and must have starred mine by
accident.

**Comment by MuLDeRiZeD** [comment]
Thanks for your quick reply!  I appreciate it really!  Good luck to you and please check out the update.  It's kind of important.  The update addresses the module used for player status.  Unfortunately, there was an error that would be generated every second in `.xsesssion-errors` so to avoid this and battery drain, I had to fix it.  You may want to update your fork too just in case! :)
